server:
    port: 80
    servlet:
        session:
            timeout: 30m
spring:
    datasource:
        username: username
        password: password
        url: jdbc:mysql://127.0.0.1:3306/restaurant?useSSL=false&CharacterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            max-lifetime: 900000
            minimum-idle: 10
    jpa:
        # 自动生成表，不过还是建议手动建
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect